Feature/create page payment and delivery
Shlov/valwax pull request #46
Opened 2023-09-14 08:18 UTC by SyroidNadiia

2023-09-14 09:08 UTC, ViraMesha commented on dictionaries/uk.json
> +      "header": {
а ти десь використовуєш header?

2023-09-14 09:08 UTC, ViraMesha commented on src/components/Typography/Typography.tsx
> +  style?: CSSProperties;
а навіщо додавати інлайнові стилі, якщо можна використовувати className? інлайнові стилі майже неможливо перебити і ними важко керувати (не можна адаптувати під екрани)

2023-09-14 09:08 UTC, ViraMesha commented on src/components/Typography/Typography.module.scss
> +.typography--variant-bodyLarge {
у нас уже є варіант типографії typography--variant-bodyL, ти можеш через проп className поміняти font-size: 24px; і line-height: 1.4; саме для свого компонента і не потрібно буде створювати додатковий варіант

2023-09-14 09:08 UTC, ViraMesha commented on src/components/Typography/Typography.module.scss
> +.typography--variant-exLargeBold {
у нас є typography--variant-subheadingBold, стилі які відрізняються, можна змінити через проп className, щоб не створювати новий варіант

2023-09-14 11:58 UTC, SyroidNadiia commented on dictionaries/uk.json
> +      "header": {
хотіла використати для встановлення головку сторінки через Head з 'next/head'
Але потім видалила, я це приберу

2023-09-14 12:01 UTC, SyroidNadiia commented on src/components/Typography/Typography.tsx
> +  style?: CSSProperties;
я не використовую інлайн стилі, це було в якості експерименту

2023-09-14 12:06 UTC, SyroidNadiia commented on src/components/Typography/Typography.module.scss
> +.typography--variant-bodyLarge {
теж про це думала, але якось дивно використати варіант, який не дуже підходить і із 3 властивостей 2 змінити. Віка обіцяла подивитися по шрифтам, бо як на мене дуже багато зайвих варіантів

2023-09-14 12:47 UTC, ViraMesha commented on dictionaries/uk.json
> +      "header": {
Я пропоную обговорити це на зустрічі з командою. Чи буде у нас заголовок один на всі сторінки, чи у кожної сторінки свій. Якщо другий варіант, то нічого видаляти не потрібно буде

2023-09-14 12:49 UTC, ViraMesha commented on src/components/Typography/Typography.tsx
> +  style?: CSSProperties;
тоді я думаю краще видалити цей проп, щоб він даремно не висів

2023-09-14 12:51 UTC, ViraMesha commented on src/components/Typography/Typography.module.scss
> +.typography--variant-bodyLarge {
цілком з тобою погоджуюся. Теж постійно звертаюся до дівчат з цією проблемою, що вони використовують ту саму назву варіанта шрифту, але у багатьох компонентах відрізняються стилі. Можна ще раз порушити це питання на спільній зустрічі.

2023-09-14 12:54 UTC, SyroidNadiia commented on dictionaries/uk.json
> +      "header": {
ok

2023-09-14 12:54 UTC, SyroidNadiia commented on src/components/Typography/Typography.tsx
> +  style?: CSSProperties;
так, я видалила, оновлю просто пізніше коли буде інформація по шрифтам

2023-09-15 18:08 UTC, ViraMesha approved these changes

2023-09-15 18:24 UTC, ViraMesha requested changes

2023-09-15 18:24 UTC, ViraMesha commented on src/components/Navigation/Navigation.module.scss
> +  padding: 35px 0;
падінг дуже сильно збільшив висоту хедера

![image](https://github.com/Shlov/valwax/assets/99128741/e3211ff9-c35a-4d0b-8b5d-892724c9fad4)

![image](https://github.com/Shlov/valwax/assets/99128741/de344082-150c-4189-b5f7-150762ba415c)

Окрім того посилання лише працює, якщо навести курсор на самий текст, якщо на падінг, то посилання не працює, просто візуально відображається курсор. Стилі з цим класом діють лише на посилання свічки. Всі інші посилання без падінгу
![image](https://github.com/Shlov/valwax/assets/99128741/60ecb160-bd07-41d4-a889-31920d3c8e9e)

2023-09-15 18:24 UTC, ViraMesha commented on src/components/Navigation/Navigation.module.scss
Посилання у бургер-меню тепер не дуже гарно виглядають (посилання на свічки має завеликий падінг)
![image](https://github.com/Shlov/valwax/assets/99128741/f3cb4ff7-8322-40eb-b37b-af9277775144)

2023-09-19 18:28 UTC, ViraMesha approved these changes

2023-09-19 18:28 UTC, merged